services:
  oauth-dummy:
    image: oven/bun:1.3.4
    volumes:
      - .:/app
    command: ["bun", "/app/tests/"]

  db:
    image: duckdb/duckdb:latest

  testing:
    build:
      context: .
      target: testing
    image: tokens:latest

  build:
    build:
      context: .
      target: build
    image: tokens:latest

  app:
    build: .
    image: tokens:latest
    ports:
      - 5454:5454
    volumes:
      - ./db:/data
