services:

  db:
    image: duckdb/duckdb:latest

  testing:
    build:
      context: .
      target: testing
    image: tokens:latest

  app:
    build: .
    image: tokens:latest
    ports:
      - 5454:5454
    volumes:
      - ./db:/data
