export const ms = (ms: number) => ms;
ms.seconds = (seconds: number) => ms(seconds * 1000);
ms.second = ms.seconds;
ms.s = ms.seconds;
ms.minutes = (minutes: number) => ms.seconds(minutes * 60);
ms.minute = ms.minutes;
ms.m = ms.minutes;
ms.hours = (hours: number) => ms.minutes(hours * 60);
ms.hour = ms.hours;
ms.h = ms.hours;
ms.days = (days: number) => ms.hours(days * 24);
ms.day = ms.days;
ms.d = ms.days;
