services:
  telemetry:
    image: jondotsoy/telemetry
    mem_limit: 68m
    cpus: 0.5
    environment:
      # - PUBLIC_URL=
      - TELEMETRY_DEBUG=true
      - GOOGLE_ANALYTICS_MODE=debug
      - GOOGLE_ANALYTICS_API_SECRET=ILU_9Q3aQOW8UnZVgpxI6Q
      - GOOGLE_ANALYTICS_MEASUREMENT_ID=G-6EBEFK218R
    ports:
      - 8080:3000

  app:
    mem_limit: 512m
    build: ..
    image: jondotsoy/token-storage:latest
    ports:
      - 5454:5454
    volumes:
      - ./db:/data
    environment:
      - METRICS_MAX_AGE_SECONDS=10
      - METRICS_AGE_BUCKETS=2
      - METRICS_ENABLE_SUMMARY=true
      - TOKENSTORAGE_TELEMETRY_URL=http://telemetry:3000/v1/collect
      - TOKENSTORAGE_TELEMETRY_DEBUG=true
      - TOKENSTORAGE_TELEMETRY_DISABLED=false
    depends_on:
      - telemetry

  prometheus:
    mem_limit: 68m
    image: prom/prometheus:latest # Use the official image
    depends_on:
      - app
    ports:
      - "9090:9090" # Map port 9090 on the host to 9090 in the container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro # Mount the config file
      # - prometheus_data:/prometheus # Mount a named volume for data persistence
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    mem_limit: 128m
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "9091:3000"
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/tokensstorage-prometheus.yml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    #   - GF_SECURITY_ADMIN_PASSWORD=your_new_password

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
